In [1]:
from sklearn import metrics

C:\Users\Admin\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\Admin\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [2]:
C = "Cat"
D = "Dog"
F = "Fox"

In [3]:
#### True Values
y_true = [C,C,C,C,C,C ,F,F,F,F,F,F,F,F,F,F, D,D,D,D,D,D,D,D,D]
#### Predicted values
y_pred = [C,C,C,C,D,F, C,C,C,C,C,C,D,D,F,F, C,C,C,D,D,D,D,D,D]

####Print the confusion matrix
print(metrics.confusion_matrix(y_true,y_pred))

####Print the precision and recall among the metrics
print(metrics.classification_report(y_true,y_pred,digits = 3))

[[4 1 1]
 [3 6 0]
 [6 2 2]]
              precision    recall  f1-score   support

         Cat      0.308     0.667     0.421         6
         Dog      0.667     0.667     0.667         9
         Fox      0.667     0.200     0.308        10

    accuracy                          0.480        25
   macro avg      0.547     0.511     0.465        25
weighted avg      0.581     0.480     0.464        25

